services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_CLUSTER_ID: "PGg8hAFeTGKg4zGfj-Ldeg"
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    restart: always
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    networks:
      - kafka_network

  darooghe-pulse:
    image: javadraziii/darooghe-pulse:0.2.3
    container_name: darooghe-pulse
    restart: always
    depends_on:
      - kafka
    environment:
      EVENT_RATE: "100"
      PEAK_FACTOR: "2.5"
      FRAUD_RATE: "0.02"
      DECLINED_RATE: "0.05"
      MERCHANT_COUNT: "50"
      CUSTOMER_COUNT: "1000"
      KAFKA_BROKER: "kafka:9092"
      EVENT_INIT_MODE: "flush"  # Options: flush, append, skip
      LOG_LEVEL: "INFO"
    tty: true
    stdin_open: true
    networks:
      - kafka_network

volumes:
  kafka_data:

networks:
  kafka_network:
    driver: bridge
